name: polynomial
description: Simple API to perform polynomial operations like finding roots, addition, subtraction, multiplication, division, etc.
version: 1.0.0
repository: https://github.com/tejainece/polynomial

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
